### ISSUE TITLE
"How" - Autist that cant download visual studio

### ISSUE THREAD

**Issue by 007Muddy** [0ez/FNBoost#1]
Hi bruh, can i ask how to run it! thanks so much

**Comment by 0ez** [comment]
compile the source with visual studio 2022, the current binary isnt working cuz im too poor to buy net reactor. i will fix it in few days if u want

**Comment by 007Muddy** [comment]
bruh can u add me on discord so can talk better? my username Muddy#8575

**Comment by 0ez** [comment]
dont add him dumb fuck says that his windows (win10 1909) is too old for vs2022
